version: '3.7'

networks:
  boilerplate-network:
    name: boilerplate-network

services:
  mysql:
    image: mysql:8.0
    container_name: boilerplate-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplatedb
      MYSQL_USER: boilerplate
      MYSQL_PASSWORD: boilerplate
    volumes:
      - /opt/docker/boilerplatedb/mysql:/var/lib/mysql:delegated
    networks:
      - boilerplate-network
    ports:
      - "8952:3306"
    restart: unless-stopped
